server {
    listen 80;
    server_name localhost;

    root /var/www/fe_sehadir/public;
    index index.php;

    limit_conn conn_limit 10;

    location / {
        limit_req zone=api_limit burst=20 nodelay;
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass app-api:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_connect_timeout 5;
        fastcgi_send_timeout 30;
        fastcgi_read_timeout 30;
    }

    # error_page 502 503 504 /index.html;
    # location = /index.html {
    #     internal;
    # }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}